---
- name: Ensure virtualenv is available system-wide
  ansible.builtin.pip:
    name: virtualenv

- name: Ensure virtualenv directory exists
  ansible.builtin.file:
    path: "{{ basics_virtenvdir }}"
    owner: root
    group: root
    mode: "0750"
    state: directory

- name: Install ansible-core into the virtualenv
  ansible.builtin.pip:
    name: "ansible-core=={{ basics_ansible_version }}"
    virtualenv: "{{ basics_virtenvdir }}"
    virtualenv_command: python3 -m venv
