---
- name: "Resolve inputs for step {{ step.id }}"
  ansible.builtin.set_fact:
    step_input: >-
      {{ step.input | default({})
         | potos.base.resolve_step_refs(steps, ansible_facts) }}
    step_run: >-
      {{ (step.when | default(true) | string)
         | potos.base.resolve_step_refs(steps, ansible_facts) | bool }}

- name: "Run step {{ step.id }}"
  ansible.builtin.include_tasks: "steps/{{ step.uses }}.yml"
  when: step_run
