---
- name: Save old hostname
  ansible.builtin.command:
    cmd: hostname
  register: potos_firstboot_old_hostname
  changed_when: false

- name: Ask hostname
  potos.base.yad:
    dialog: form
    title: "{{ potos_firstboot_client_name }} Hostname"
    text: |
      Please enter your hostname below.
    fullscreen: true
    borders: 20
    align: center
    image: "{{ potos_firstboot_logo }}"
    image_on_top: true
    fields:
      - label: Hostname
    buttons:
      - label: OK
        id: 0
      - label: Change keyboard layout
        action: "{{ potos_firstboot_setup_dir }}/change-keyboard-layout.sh"
    validations:
      - type: required
        field: Hostname
        error_message: Please choose the hostname.
      - type: regex
        field: Hostname
        pattern: "^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$"
        error_message: >-
          Hostname is invalid! Make sure it only contains lowercase letters, digits and
          hyphens. It must not start or end with a hyphen, and be at most 63 characters long.
    max_attempts: 0
  register: potos_firstboot_hostname_dialog
  when:
    - potos_firstboot_hostname is undefined
    - potos_firstboot_ask_hostname
  tags:
    - "molecule-notest"

- name: Set hostname from dialog as an ansible fact
  ansible.builtin.set_fact:
    potos_firstboot_hostname: "{{ potos_firstboot_hostname_dialog.value }}"
  when:
    - potos_firstboot_hostname is undefined
    - potos_firstboot_ask_hostname
  tags:
    - "molecule-notest"

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ potos_firstboot_hostname }}"
  when:
    - potos_firstboot_hostname is defined
    - potos_firstboot_ask_hostname

- name: Adjust hosts file
  ansible.builtin.replace:
    path: "/etc/hosts"
    regexp: "{{ potos_firstboot_old_hostname.stdout }}"
    replace: "{{ potos_firstboot_hostname }}"
  when:
    - potos_firstboot_hostname is defined
    - potos_firstboot_old_hostname.stdout != ''
    - potos_firstboot_ask_hostname
