---
- name: Get default username
  ansible.builtin.shell:
    cmd: |
      awk -v val=1000 -F ":" '$3==val{print $1}' /etc/passwd
  register: potos_firstboot_initial_username
  changed_when: false
  when:
    - potos_firstboot_initial_user_delete_admin_iso_user

- name: Ask new user
  potos.base.yad:
    dialog: form
    title: "{{ potos_firstboot_client_name }} Setup"
    text: |
      IMPORTANT: If your password contains special characters, please remember
      to select the appropriate keyboard layout first.

      Please enter your new credentials below.
    fullscreen: true
    borders: 20
    align: center
    image: "{{ potos_firstboot_logo }}"
    image_on_top: true
    fields:
      - label: Username
      - label: Password
        type: H
      - label: Confirm password
        type: H
    buttons:
      - label: OK
        id: 0
      - label: Change keyboard layout
        action: "{{ potos_firstboot_setup_dir }}/change-keyboard-layout.sh"
    validations:
      - type: required
        field: Username
        error_message: Please choose and enter your new credentials.
      - type: required
        field: Password
        error_message: Please choose and enter your new credentials.
      - type: match
        field: Password
        match: Confirm password
        error_message: Your password was not identical. Please try again.
    max_attempts: 0
  register: potos_firstboot_new_user_password
  changed_when: false
  no_log: true
  when: potos_firstboot_local_user_add
  tags:
    - "molecule-notest"

- name: Add local groups
  ansible.builtin.group:
    name: "{{ item }}"
    system: true
  loop: "{{ potos_firstboot_local_groups }}"
  when:
    - potos_firstboot_local_groups is defined
    - potos_firstboot_local_groups is iterable
    - potos_firstboot_local_groups is not string
    - potos_firstboot_local_groups is not mapping
  tags:
    - "molecule-notest"

- name: use potos_firstboot_local_user_groups list
  ansible.builtin.set_fact:
    potos_firstboot_local_user_groups_list: "{{ potos_firstboot_local_user_groups }}"
  when:
    - potos_firstboot_local_user_add
    - potos_firstboot_local_user_groups is defined
    - potos_firstboot_local_user_groups is iterable
    - potos_firstboot_local_user_groups is not string
    - potos_firstboot_local_user_groups is not mapping

- name: use empty group list, potos_firstboot_local_user_groups unset or invalid
  ansible.builtin.set_fact:
    potos_firstboot_local_user_groups_list: []
  when: potos_firstboot_local_user_groups_list is not defined

- name: Add local user with secondary group memberships
  ansible.builtin.user:
    name: "{{ potos_firstboot_new_user_password.fields['Username'] }}"
    password: "{{ potos_firstboot_new_user_password.fields['Password'] | password_hash('sha512') }}"
    groups: "{{ potos_firstboot_local_user_groups_list | join(',') }}"
    shell: "{{ potos_firstboot_local_user_add_shell }}"
  no_log: true
  when:
    - potos_firstboot_local_user_add
  tags:
    - "molecule-notest"
