---
galaxy_info:
  author: Project Potos
  description: UKI setup for Potos Linux Clients
  company: Project Potos
  license: GPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - potos
    - base
    - secureboot
    - uki

dependencies: []
