---
argument_specs:
  main:
    short_description: Install the base setup required for Potos periodic ansible runs.
    description:
      - This role sets up the base environment for Potos Linux Clients, including
        periodic ansible run timers, a wrapper script for ansible-pull, a Python
        virtualenv with ansible-core installed, and log rotation.
    options:
      potos_basics_client_name:
        type: str
        default: potos
      potos_basics_etc_dir:
        type: str
        default: /etc/potos
      potos_basics_state_dir:
        type: str
        default: /var/lib/potos
      potos_basics_workdir:
        type: str
        default: /var/lib/potos/ansible
      potos_basics_virtenvdir:
        type: str
        default: /var/lib/potos/virtenv
      potos_basics_logdir:
        type: str
        default: /var/log/potos
      potos_basics_libexec_dir:
        type: str
        default: /usr/libexec/potos
      potos_basics_inventory:
        type: str
        default: /var/lib/potos/ansible/potos_inventory
      potos_basics_config_file:
        type: str
        default: /etc/potos/config.yml
      potos_basics_specs_token_backend:
        type: str
        default: file
        choices: [file, systemd-creds]
      potos_basics_specs_token_file:
        type: str
        default: /etc/potos/specs_token
      potos_basics_specs_token_name:
        type: str
        default: specs-token
      potos_basics_ansible_vault_key_backend:
        type: str
        default: file
        choices: [none, file, systemd-creds]
      potos_basics_ansible_vault_key_file:
        type: str
        default: /etc/potos/ansible_vault_key
      potos_basics_ansible_vault_key_name:
        type: str
        default: ansible-vault-key
      potos_basics_specs_url:
        type: str
        default: ""
      potos_basics_specs_branch:
        type: str
        default: main
      potos_basics_specs_clone_dir:
        type: str
        default: /var/lib/potos/specs
      potos_basics_specs_galaxy_dir:
        type: str
        default: /var/lib/potos/specs/.galaxy
      potos_basics_runtypes:
        type: list
        elements: dict
        default:
          - { runtype: daily, on_calendar: daily }
          - { runtype: hourly, on_calendar: hourly }
        options:
          runtype:
            type: str
            required: true
          on_calendar:
            type: str
            required: false
      potos_basics_timer_activate:
        type: bool
        default: false
      potos_basics_always_verbose:
        type: bool
        default: false
      potos_basics_enable_reboot_reminder:
        type: bool
        default: true
      potos_basics_reboot_reminder_days:
        type: int
        default: 10
      potos_basics_on_error_additional_lines:
        type: list
        elements: str
        default: []
      potos_basics_packages_enforce_latest:
        type: bool
        default: false
