---
- name: Prompt the user for the specs-repo token
  ansible.builtin.command:
    cmd: >-
      yad --fullscreen --title '{{ potos_firstboot_client_name }} credentials'
      --borders=20 --align=center --button=gtk-ok
      --image-on-top --image=/setup/logo.png
      --text "Please paste the access token for the specs repository below."
      --form --field=Token:H
  register: potos_firstboot_credentials_prompt
  changed_when: false
  no_log: true
  tags:
    - molecule-notest

- name: Capture the prompted token
  ansible.builtin.set_fact:
    potos_firstboot_credentials_token: >-
      {{ potos_firstboot_credentials_prompt.stdout | trim }}
  no_log: true
